### ISSUE TITLE
ConcurrentModificationException 报错

### ISSUE THREAD

**Issue by ParkSouth** [dueeeke/DKVideoPlayer#196]
2019-03-13 13:59:07.390 11562-11585/? E/CrashReport: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.dueeeke.videoplayer.player.IjkVideoView.setPlayState(IjkVideoView.java:111)
        at com.dueeeke.videoplayer.player.BaseIjkVideoView.i(BaseIjkVideoView.java:442)
        at com.dueeeke.videoplayer.player.c$2.onError(IjkPlayer.java:253)
        at tv.danmaku.ijk.media.player.AbstractMediaPlayer.notifyOnError(AbstractMediaPlayer.java:106)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler.handleMessage(IjkMediaPlayer.java:1020)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by dueeeke** [comment]
你有没有修改过源码

**Comment by ParkSouth** [comment]
> 你有没有修改过源码
没用修改源码  只是把你的so 换成了我的

**Comment by ParkSouth** [comment]
@dueeeke

**Comment by dueeeke** [comment]
是必现吗

**Comment by ParkSouth** [comment]
@dueeeke  是的 只要流停止了  出现了error 然后我重新赋值  就出现
case IjkVideoView.STATE_ERROR:
					if (isVideoError) {
						initVideo();
						isVideoError = !isVideoError;
					}
					break;

**Comment by dueeeke** [comment]
initVideo()你是怎么写的

**Comment by dueeeke** [comment]
是不是重新添加了播放状态的监听？

**Comment by ParkSouth** [comment]
@dueeeke 
IjkPlayer ijkPlayer = new IjkPlayer(this);
ijkPlayer.setVideoConfiguration(false);
video_view.setPlayerConfig(new PlayerConfig.Builder()
		  .autoRotate()
		  .setCustomMediaPlayer(ijkPlayer)
		  .build());
video_view.setUrl(mFileUrl);
video_view.start();
video_view.setScreenScale(IjkVideoView.SCREEN_SCALE_MATCH_PARENT);
video_view.addOnVideoViewStateChangeListener(mOnVideoViewStateChangeListener);

**Comment by ParkSouth** [comment]
确实重新添加了播放状态的监听

**Comment by ParkSouth** [comment]
稍等  我是试下

**Comment by dueeeke** [comment]
集合遍历的时候添加或者删除元素就会出现 java.util.ConcurrentModificationException 此异常，如果想出错是重新开始播放，直接调用ijkVideoView的retry方法即可

**Comment by ParkSouth** [comment]
是这样的  我这有个模式  你切换一个模式的时候  直播流  会断开停止推流  播放器机会报Error  所以我就用这个方法  我等会试一下retry  还有一个问题 用 pause  再用 resume 直播流  播放不起来  我只能用release 然后重新播一次

**Comment by dueeeke** [comment]
这个只能按照你这样处理，一般来说直播流恢复播放都是去重新加载流地址，因为直播要保持实时性

**Comment by ParkSouth** [comment]
问题解决了 retry 谢谢
