### ISSUE TITLE
画中画崩溃问题

### ISSUE THREAD

**Issue by iYang9683** [dueeeke/DKVideoPlayer#236]
demo首页--“画中画”--”画中画“这个activity。打开这个activity，然后退出再迅速重进这activity就会Crash
```
05-04 11:56:14.391 20109-20109/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dueeeke.dkplayer, PID: 20109
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dueeeke.dkplayer/com.dueeeke.dkplayer.activity.pip.PIPActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
     Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4419)
        at android.view.ViewGroup.addView(ViewGroup.java:4260)
        at android.view.ViewGroup.addView(ViewGroup.java:4200)
        at android.view.ViewGroup.addView(ViewGroup.java:4173)
        at com.dueeeke.dkplayer.activity.pip.PIPActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6861)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6365) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791) 
```

**Comment by lyx0224** [comment]
在 playerContainer.addView(ijkVideoView)上面增加：
if(ijkVideoView.getParent() != null) {
            ((ViewGroup)ijkVideoView.getParent()).removeView(ijkVideoView);
        }
就好了。
