### ISSUE TITLE
android 10兼容问题

### ISSUE THREAD

**Issue by liweiGe** [dueeeke/DKVideoPlayer#326]
exo 内核的在android 10上播放失败, ijk 内核的可以播放
拿的是demo验证的,exo 是2.9.6 版本

**Comment by liweiGe** [comment]
> 试试3.0.4版

还是一样,最新的2.10.4版本的exo还是播放失败

**Comment by dueeeke** [comment]
报什么错误

**Comment by liweiGe** [comment]
![image](https://user-images.githubusercontent.com/25901728/65668927-36ff3080-e075-11e9-94f2-371c0c2b2183.png)
2019-09-26 15:48:16.321 13655-13803/com.dueeeke.dkplayer E/ion: ioctl c0044901 failed with code -1: Invalid argument
2019-09-26 15:48:16.346 13655-13788/com.dueeeke.dkplayer E/AudioTrack: getMinFrameCount(): Unable to query output sample rate for stream type -1; status -1
2019-09-26 15:48:16.346 13655-13788/com.dueeeke.dkplayer E/AudioTrack-JNI: AudioTrack::getMinFrameCount() for sample rate 44100 failed with status -1
2019-09-26 15:48:16.346 13655-13788/com.dueeeke.dkplayer E/android.media.AudioTrack: getMinBufferSize(): error querying hardware
2019-09-26 15:48:16.350 13655-13788/com.dueeeke.dkplayer E/IAudioFlinger: createTrack returned error -38
2019-09-26 15:48:16.350 13655-13788/com.dueeeke.dkplayer E/AudioTrack: createTrack_l(0): AudioFlinger could not create track, status: -38 output 1073741825
2019-09-26 15:48:16.351 13655-13788/com.dueeeke.dkplayer E/AudioTrack-JNI: Error -38 initializing AudioTrack
2019-09-26 15:48:16.351 13655-13788/com.dueeeke.dkplayer D/AudioTrack: gather(): no metrics gathered, track status=-38
2019-09-26 15:48:16.351 13655-13788/com.dueeeke.dkplayer E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
2019-09-26 15:48:16.353 13655-13788/com.dueeeke.dkplayer E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:738)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1507)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1415)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:514)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:595)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:732)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1507) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2019-09-26 15:48:16.356 13655-13655/com.dueeeke.dkplayer E/DKPlayer: STATE_ERROR
