### ISSUE TITLE
开启缓存报错

### ISSUE THREAD

**Issue by dlvip** [dueeeke/DKVideoPlayer#342]
com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/package/cache/video-cache/1000k/hls/index.m3u8: open failed: ENOENT (No such file or directory)
                                                                           at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
                                                                           at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
                                                                           at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
                                                                           at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                           at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                           at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
                                                                           at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
                                                                           at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                           at java.lang.Thread.run(Thread.java:784)
                                                                        Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/package/cache/video-cache/1000k/hls/index.m3u8: open failed: ENOENT (No such file or directory)
                                                                           at libcore.io.IoBridge.open(IoBridge.java:485)
                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288)
                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151)
                                                                           at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
                                                                           at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
                                                                           at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
                                                                           at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
                                                                           at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
                                                                           at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156) 
                                                                           at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                           at java.lang.Thread.run(Thread.java:784) 
                                                                        Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                           at libcore.io.Linux.open(Native Method)
                                                                           at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
                                                                           at libcore.io.IoBridge.open(IoBridge.java:471)
                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288) 
                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151) 
                                                                           at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65) 
                                                                           at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
                                                                           at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
                                                                           at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
                                                                           at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
                                                                           at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156) 
                                                                           at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                           at java.lang.Thread.run(Thread.java:784)

**Comment by dueeeke** [comment]
目前的缓存实现是不支持m3u8的缓存的

**Comment by dlvip** [comment]
好吧  谢谢  有没有什么方案呢？

**Comment by dueeeke** [comment]
使用exo自己的缓存机制可以缓存m3u8，目前我已经实现，不过还未发布，切到dev可以查看

**Comment by dueeeke** [comment]
请使用3.1.0，具体方法在demo里有
