### ISSUE TITLE
读取raw视频，在5.0系统版本读取视频失败 ，但是在7.0及以上系统都是可以正常读取播放的，这个是什么原因，报错日志信息如下

### ISSUE THREAD

**Issue by 13763040504** [dueeeke/DKVideoPlayer#350]
`09-30 16:14:28.007 701-701/? E/MediaPlayer: setDataSource: IOException! uri=android.resource://com.gh.eloan.launcher/604438528
    java.io.FileNotFoundException: No package found for authority: android.resource://com.gh.eloan.launcher/604438528
        at android.content.ContentResolver.getResourceId(ContentResolver.java:1264)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:980)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:919)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1003)
        at com.dueeeke.videoplayer.player.AndroidMediaPlayer.setDataSource(AndroidMediaPlayer.java:39)
        at com.dueeeke.videoplayer.player.VideoView.prepareDataSource(VideoView.java:323)
        at com.dueeeke.videoplayer.player.VideoView.startPrepare(VideoView.java:307)
        at com.dueeeke.videoplayer.player.VideoView.replay(VideoView.java:447)
        at com.dueeeke.videoplayer.controller.BaseVideoController$1.onClick(BaseVideoController.java:93)
        at android.view.View.performClick(View.java:4874)
        at android.view.View$PerformClick.run(View.java:20341)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5958)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)`

**Comment by dueeeke** [comment]
建议使用exoplayer,如果还是不行用ijk
