### ISSUE TITLE
exoplayer 播放多个视频黑屏

### ISSUE THREAD

**Issue by xiexk** [dueeeke/DKVideoPlayer#392]
2019-11-26 19:27:01.325 21693-10827/com.tc.smlite E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
2019-11-26 19:27:01.330 21693-10827/com.tc.smlite I/ACodec: codec does not support config priority (err -1010)
2019-11-26 19:27:01.336 21693-10827/com.tc.smlite D/SurfaceUtils: set up nativeWindow 0xc3f43808 for 1920x1080, color 0x11, rotation 0, usage 0x2002900
2019-11-26 19:27:01.336 21693-10827/com.tc.smlite W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
2019-11-26 19:27:01.337 21693-10827/com.tc.smlite W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
2019-11-26 19:27:01.338 21693-10827/com.tc.smlite W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
2019-11-26 19:27:01.348 21693-10827/com.tc.smlite E/BufferQueueProducer: [SurfaceTexture-1-21693-13466] dequeueBuffer: createGraphicBuffer failed
2019-11-26 19:27:01.348 21693-10827/com.tc.smlite E/ACodec: dequeueBuffer failed: Out of memory (12)
2019-11-26 19:27:01.348 21693-10827/com.tc.smlite E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xfffffff4)
2019-11-26 19:27:01.348 21693-10827/com.tc.smlite E/ACodec: signalError(omxError 0x80001001, internalError -12)
2019-11-26 19:27:01.348 21693-10826/com.tc.smlite E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 5

**Comment by dueeeke** [comment]
oom，你这什么配置的机器

**Comment by xiexk** [comment]
设备型号 :SM-8设备  SN :gosurf_proi00008
CPU芯片 :Amlogic注册  I D :gosurf_proi00008
运行内存 :1835638784设备  I P :192.168.8.104
储存空间 :12227362816设备MAC :80:5E:4F:D2:08:5D
设备时区 :GMT+08:00OS版本 :7.1.2
设备时间 :2019-11-27 19:21:49
GPU1 :Mali-T820GPU2 :
GPU3 :SSD :q9377

**Comment by xiexk** [comment]
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 25.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:516)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:737)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:648)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 25.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:790)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:514)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1190) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:737) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:648) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:1991)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:854)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:783)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:514) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1190) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:737) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:648) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 


更新3.2版本后 同时播两个本地视频 用exo内核播放  报的错

**Comment by dueeeke** [comment]
推荐你用ijk

**Comment by xiexk** [comment]
用过 多视频同时播放 每个视频是个列表 后面会越播越卡  谢谢了 我再试试把

**Comment by dueeeke** [comment]
你这设备看起来不像是手机，配置应该很低吧，我不建议多开，如果硬是要这样，那只能靠你自己去优化了

**Comment by xiexk** [comment]
好的
